project:
  model: beta
  host:
    eureka1: 172.22.128.81
    eureka2: 172.22.128.82
    eureka3: 172.22.128.83

server:
  port: 8761

spring:
  application:
    name: eureka-server
  freemarker:
    prefer-file-system-access: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${project.host.eureka1}:${server.port}/eureka/,http://${project.host.eureka2}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
