project:
  model: beta
  host:
    eureka1: 127.0.0.1
    eureka2: 127.0.0.1
    eureka3: 127.0.0.1

server:
  port: 10086

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${project.host.eureka1}:8761/eureka/,http://${project.host.eureka3}:10087/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
