project:
  model: beta
  host:
    eureka1: 172.22.128.81
    eureka2: 172.22.128.82
    eureka3: 172.22.128.83

server:
  port: 9200
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connection: 15000

spring:
  application:
    name: eureka-server

eureka:
  environment: ${project.model}
  instance:
    hostname: ${project.host.eureka1}
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${project.host.eureka2}:${server.port}/eureka/,http://${project.host.eureka3}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
