server:
  port: 8090

spring:
  application:
    name: service-provider

eureka:
  client:
    service-url:
      defaultZone: http://172.22.128.81:9200/eureka/,http://172.22.128.82:9200/eureka/,http://172.22.128.83:9200/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # \u6BCF\u96945\u79D2\u53D1\u9001\u4E00\u6B21\u5FC3\u8DF3
    lease-expiration-duration-in-seconds: 10 # 10\u79D2\u4E0D\u53D1\u9001\u5C31\u8FC7\u671F
    prefer-ip-address: true  #\u5F53\u4F60\u83B7\u53D6host\u65F6\uFF0C\u8FD4\u56DE\u7684\u4E0D\u662F\u4E3B\u673A\u540D\uFF0C\u800C\u662Fip
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
